[package]
name = "foghorn_widgets"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
iced_widget.workspace = true

tracing.workspace = true
tracing.features = ["log"]

unicode-segmentation.workspace = true
